<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DocumentRepositoriesSeeder extends Seeder
{
    public function run(): void
    {
        $types = ['Case Study', 'Thesis', 'Proposal', 'Capstone', 'System Studies'];

        DB::table('document_repositories')->insert([
            [
                'title' => 'Case Study on Local Business Process Improvement',
                'student_id' => 1,
                'teacher_id' => 2,
                'approved_by' => 3,
                'citation' => 'Dela Cruz, M. (2024). Business Process Improvement.',
                'metadata' => json_encode(['keywords' => ['business', 'process', 'case study']]),
                'file' => null,
                'status' => 'pending',
                'date_submitted' => now(),
                'date_reviewed' => null,
                'abandoned_date' => null,
                'recovered_date' => null,
                'lost_date' => null,
                'study_type' => $types[array_rand($types)],
                'archived' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Thesis: Enhanced Learning Management System',
                'student_id' => 1,
                'teacher_id' => 5,
                'approved_by' => 3,
                'citation' => 'Lopez, A. (2023). Learning Management Systems.',
                'metadata' => json_encode(['keywords' => ['LMS', 'education tech']]),
                'file' => null,
                'status' => 'reviewed',
                'date_submitted' => now()->subDays(4),
                'date_reviewed' => now()->subDays(2),
                'abandoned_date' => null,
                'recovered_date' => null,
                'lost_date' => null,
                'study_type' => $types[array_rand($types)],
                'archived' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Proposal: Campus Smart ID System',
                'student_id' => 1,
                'teacher_id' => 2,
                'approved_by' => 6,
                'citation' => 'Reyes, J. (2024). Smart Identification Systems.',
                'metadata' => json_encode(['keywords' => ['ID system', 'automation']]),
                'file' => null,
                'status' => 'pending',
                'date_submitted' => now()->subDays(8),
                'date_reviewed' => null,
                'abandoned_date' => null,
                'recovered_date' => null,
                'lost_date' => null,
                'study_type' => $types[array_rand($types)],
                'archived' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Capstone: Online Booking System for School Offices',
                'student_id' => 1,
                'teacher_id' => 5,
                'approved_by' => 3,
                'citation' => 'Torres, L. (2022). Online Booking Solutions.',
                'metadata' => json_encode(['keywords' => ['booking', 'web system']]),
                'file' => null,
                'status' => 'pending',
                'date_submitted' => now()->subDays(12),
                'date_reviewed' => null,
                'abandoned_date' => null,
                'recovered_date' => null,
                'lost_date' => null,
                'study_type' => $types[array_rand($types)],
                'archived' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'System Study: Multi-Branch Inventory System',
                'student_id' => 1,
                'teacher_id' => 5,
                'approved_by' => 3,
                'citation' => 'Flores, C. (2021). Inventory Optimization.',
                'metadata' => json_encode(['keywords' => ['inventory', 'branches']]),
                'file' => null,
                'status' => 'pending',
                'date_submitted' => now()->subDays(20),
                'date_reviewed' => null,
                'abandoned_date' => null,
                'recovered_date' => null,
                'lost_date' => null,
                'study_type' => $types[array_rand($types)],
                'archived' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Case Study: Productivity Monitoring System',
                'student_id' => 1,
                'teacher_id' => 2,
                'approved_by' => 6,
                'citation' => 'Castillo, T. (2023). Productivity Monitoring.',
                'metadata' => json_encode(['keywords' => ['productivity', 'monitoring']]),
                'file' => null,
                'status' => 'reviewed',
                'date_submitted' => now()->subDays(25),
                'date_reviewed' => now()->subDays(23),
                'abandoned_date' => null,
                'recovered_date' => null,
                'lost_date' => null,
                'study_type' => $types[array_rand($types)],
                'archived' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Thesis: Drone-Assisted Delivery System',
                'student_id' => 1,
                'teacher_id' => 5,
                'approved_by' => 3,
                'citation' => 'Valdez, R. (2024). Drone Delivery Solutions.',
                'metadata' => json_encode(['keywords' => ['drones', 'delivery']]),
                'file' => null,
                'status' => 'pending',
                'date_submitted' => now()->subDays(30),
                'date_reviewed' => null,
                'abandoned_date' => null,
                'recovered_date' => null,
                'lost_date' => null,
                'study_type' => $types[array_rand($types)],
                'archived' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Proposal: Automated Gate Access System',
                'student_id' => 1,
                'teacher_id' => 2,
                'approved_by' => 3,
                'citation' => 'Santos, K. (2023). Gate Automation Technologies.',
                'metadata' => json_encode(['keywords' => ['gate', 'security system']]),
                'file' => null,
                'status' => 'pending',
                'date_submitted' => now()->subDays(35),
                'date_reviewed' => null,
                'abandoned_date' => null,
                'recovered_date' => null,
                'lost_date' => null,
                'study_type' => $types[array_rand($types)],
                'archived' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'Capstone: Mobile Application for School Announcements',
                'student_id' => 1,
                'teacher_id' => 5,
                'approved_by' => 3,
                'citation' => 'Tan, L. (2024). Mobile Communication Systems.',
                'metadata' => json_encode(['keywords' => ['mobile app', 'announcements']]),
                'file' => null,
                'status' => 'pending',
                'date_submitted' => now()->subDays(40),
                'date_reviewed' => null,
                'abandoned_date' => null,
                'recovered_date' => null,
                'lost_date' => null,
                'study_type' => $types[array_rand($types)],
                'archived' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'title' => 'System Study: Digital Archiving System',
                'student_id' => 1,
                'teacher_id' => 2,
                'approved_by' => 6,
                'citation' => 'Aquino, R. (2022). Archiving Processes.',
                'metadata' => json_encode(['keywords' => ['archive', 'documents']]),
                'file' => null,
                'status' => 'reviewed',
                'date_submitted' => now()->subDays(50),
                'date_reviewed' => now()->subDays(49),
                'abandoned_date' => null,
                'recovered_date' => null,
                'lost_date' => null,
                'study_type' => $types[array_rand($types)],
                'archived' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
